apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9-lvm
spec:
  source:
      http:
        url: http://198.18.10.1:8800/rhel9_uefi.qcow2
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 22Gi
    volumeMode: Block
    storageClassName: lvms-vg-nvme
