apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9
spec:
  source:
      http:
         url: http://192.168.0.1:8000/rhel9.qcow2
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 21Gi
    volumeMode: Block
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
