apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9-parent
spec:
  source:
      http:
         url: http://10.16.29.214:8080/rhel9.4.qcow2
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 21Gi
    volumeMode: Block
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
