apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-dedicate-io
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha3"], "image": "kubevirt/sidecar-shim:20240108_99b6c4bdb", "configMap": {"name": "sidecar-script", "key": "my_script.sh", "hookPath": "/usr/bin/onDefineDomain"}}]'
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      annotations:
        cdi.kubevirt.io/smartCloneFromExistingSnapshot: default/vsnapshot
      name: dedicate-a
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 22Gi
        volumeMode: Block
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
      source:
        snapshot:
          namespace: default
          name: rhel9-snap
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: dedicate-b
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        volumeMode: Block
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
      source:
        blank: {}
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: dedicate-c
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        volumeMode: Block
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9
    spec:
      domain:
        ioThreadsPolicy: auto
        cpu:
          cores: 16
        devices:
          disks:
          - disk:
              bus: virtio
            name: dedicate-a
            dedicatedIOThread: true
          - disk:
              bus: virtio
            name: dedicate-b
            dedicatedIOThread: true
          - disk:
              bus: virtio
            name: dedicate-c
            dedicatedIOThread: true
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        resources:
          requests:
            memory: 128Gi
            cpu: 16
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
        - name: dedicate-a
          dataVolume:
            name: dedicate-a
        - name: dedicate-b
          dataVolume:
            name: dedicate-b
        - name: dedicate-c
          dataVolume:
            name: dedicate-c
