apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-lvm
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: rhel9-lvm
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 22Gi
        volumeMode: Block
        storageClassName: lvms-vg-nvme
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: dedicate-b-lvm
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Gi
        volumeMode: Block
        storageClassName: lvms-vg-nvme
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9
    spec:
      domain:
        ioThreadsPolicy: auto
        cpu:
          cores: 16
        devices:
          disks:
          - disk:
              bus: virtio
            name: rhel9-lvm
            dedicatedIOThread: true
          - disk:
              bus: virtio
            name: dedicate-b-lvm
            dedicatedIOThread: true
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        resources:
          requests:
            memory: 64Gi
            cpu: 16
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rhel9-lvm
          dataVolume:
            name: rhel9-lvm
        - name: dedicate-b-lvm
          dataVolume:
            name: dedicate-b-lvm
