apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      enforcedBodySizeLimit: 20MB
      retention: 1h
      resources:
        requests:
          cpu: 6
          memory: 25Gi
