apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker026-1029p
spec:
  capacity:
    storage: 894Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: promdb-pv
  local:
    path: /var/promdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker026-1029p
