apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker111-r650
spec:
  capacity:
    storage: 2900Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: promdb-pv
  local:
    path: /var/promdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker111-r650
