apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
  - name: hpp-nvmes
    path: "/mnt/hpp-pool"
  workload:
    nodeSelector:
      kubernetes.io/workers: "vm-workload"
