apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
  - name: hpp-nvmes
    path: "/var/mnt/nvme-hpp"
workload:
  nodeSelector:
    kubernetes.io/workers: "vm-workload"
