apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hpp-nvmes
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePool: hpp-nvmes
