apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-public-network
  namespace: openshift-storage
spec:
  config: '{
   "cniVersion": "0.3.1",
   "type": "macvlan",
   "master": "eno12409np1",
   "mode": "bridge",
   "ipam": {
      "type": "whereabouts",
      "range": "192.168.4.1/22"
   }
  }'
