apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-openshift-machineconfig-worker-schedstats-karg
spec:
  kernelArguments:
    - schedstats=enable
    - sched.schedstats=enable
