apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker011-1029p
          - worker012-1029p
          - worker013-1029p
  storageClassDevices:
    - storageClassName: "local-volume-fs"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/nvme0n1
