apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-volume-block"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker005-1029p
          - worker006-1029p
          - worker007-1029p
  storageClassDevices:
    - storageClassName: "local-volume-block"
      volumeMode: Block
      devicePaths:
        - /dev/nvme0n1
