apiVersion: v1
kind: Namespace
metadata:
  name: multiclusterengine
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multiclusterengine
spec:
  targetNamespaces:
  - multiclusterengine
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable-$VERSION
  installPlanApproval: Automatic
  name: multicluster-engine
