apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: nvme-lvmcluster
spec:
  storage:
    deviceClasses:
    - name: vg-nvme
      deviceSelector:
        paths:
        - /dev/disk/by-path/pci-0000:01:00.0-nvme-1 
      thinPoolConfig:
        name: nvme-thin-pool
        sizePercent: 90
        overprovisionRatio: 10
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker002-1029p
              - worker003-1029p
              - worker004-1029p

