apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - default: true
      deviceSelector:
        paths:
        - /dev/vdb
      name: standard
      thinPoolConfig:
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90
    - deviceSelector:
        paths:
        - /dev/vdc
      name: fast
      thinPoolConfig:
        name: thin-pool-2
        overprovisionRatio: 10
        sizePercent: 90
